version: "3"

services:
  docker-react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/app
    ports:
      - "3003:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
